Feature/browse documents
BloomTech-Labs/human-rights-first-docdb-fe pull request #29
Opened 2021-11-16 21:30 UTC by fervelgo

## Coauthors
Jacob Shomali
Fernando Velasco

## Description

We added a default search value to the "getDsData" function such that we load a default set of documents when a user signs in.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2021-11-16 21:37 UTC, HeyAnwar approved these changes
Great work !!

2021-11-16 21:38 UTC, collerhatguy approved these changes
Its ready spaghetti

2021-11-16 21:42 UTC, juliane1999 approved these changes
Great work!

2021-11-16 22:05 UTC, bevanger approved these changes
Great job getting this feature added. The code looks great

2021-11-16 22:24 UTC, rkshockey requested changes
I checked with Paul about the .env.sample document - it should have the variable names, but they should be equal to example variables and not what we're actually using! The client id and uri's should not be up here.

2021-11-16 22:24 UTC, rkshockey commented on .env.sample
> +REACT_APP_CLIENT_ID=0oavso7p45Q1PRKSk4x6
Only the variable names here should be the real thing!

2021-11-16 22:47 UTC, fervelgo reviewed
Ready ready ready

2021-11-16 22:53 UTC, rkshockey approved these changes

2021-11-17 00:25 UTC, BradfordMez approved these changes
Great job y'all! Smart idea adding a default search! Looks good!

2021-11-17 01:29 UTC, RimshaSaleem approved these changes

2021-11-17 05:18 UTC, merged