Feature/bordered cards list view
BloomTech-Labs/human-rights-first-docdb-fe pull request #63
Opened 2021-12-16 20:35 UTC by allisonhomem

## Description

<a href="https://www.loom.com/share/dbee91518a9b4d519fb53a0ea90ff082">
    <p>Loom Message - 16 December 2021 - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/dbee91518a9b4d519fb53a0ea90ff082-with-play.gif">
  </a>

Added styling to list-view cards to match grid-view cards for web app consistency.

Fixes # (background color only on portion of loading page screen)

Changed view height of loading spinner container so that background color covers entire screen. Center spinner on screen to mimic traditional loading pages.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2021-12-16 21:06 UTC, mgreenwaldm approved these changes

2021-12-16 22:08 UTC, Bobby-Tav approved these changes
The code looks nice and clean. I like the the List view is uniformed with the rest of the project.

2021-12-17 00:57 UTC, Klove-A requested changes
I am not entirely sure what "build / Run Lint on source (pull_request)" is referring to but we should address it before merging this.
It seems to be running into an error when starting up.

2021-12-20 18:16 UTC, SomeiLam approved these changes
Thanks for putting nice styling to the application. The code looks clean and the video was easy to understand.

2021-12-20 18:34 UTC, Klove-A approved these changes

2021-12-20 18:51 UTC, merged